<?php

namespace Database\Seeders;

use App\Models\Address;
use App\Models\Client;
use App\Models\Property;
use App\Models\PropertyListing;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ApprovedPropertyListingSeeder extends Seeder
{
    /**
     * Seed 10 approved property listings so they appear in the homepage carousel.
     */
    public function run(): void
    {
        $items = [
            [
                'full_name' => 'Aarav Shrestha',
                'mobile_no' => '9800000001',
                'citizenship_no' => '12-01-75-00001',
                'province' => 'Bagmati',
                'district' => 'Kathmandu',
                'municipality' => 'Kathmandu Metropolitan City',
                'ward_no' => '32',
                'tole_locality' => 'Boudha',
                'property_type' => 'house',
                'property_code' => 'PROP-APP-001',
                'area' => '1200 sqft',
                'covered_area' => '1100 sqft',
                'no_of_floors' => 3,
                'purpose_of_listing' => 'sale',
                'expected_selling_price' => 8500000,
                'minimum_acceptable_price' => 8000000,
                'rental_amount' => null,
                'application_no' => 'AGJ-202608-0001',
            ],
            [
                'full_name' => 'Sushma Gurung',
                'mobile_no' => '9800000002',
                'citizenship_no' => '12-01-75-00002',
                'province' => 'Bagmati',
                'district' => 'Lalitpur',
                'municipality' => 'Lalitpur Metropolitan City',
                'ward_no' => '11',
                'tole_locality' => 'Patan',
                'property_type' => 'apartment',
                'property_code' => 'PROP-APP-002',
                'area' => '2 BHK',
                'covered_area' => '900 sqft',
                'no_of_floors' => 4,
                'purpose_of_listing' => 'sale',
                'expected_selling_price' => 9600000,
                'minimum_acceptable_price' => 9100000,
                'rental_amount' => null,
                'application_no' => 'AGJ-202608-0002',
            ],
            [
                'full_name' => 'Bikash Karki',
                'mobile_no' => '9800000003',
                'citizenship_no' => '12-01-75-00003',
                'province' => 'Gandaki',
                'district' => 'Kaski',
                'municipality' => 'Pokhara Metropolitan City',
                'ward_no' => '18',
                'tole_locality' => 'Lake Side',
                'property_type' => 'land',
                'property_code' => 'PROP-APP-003',
                'area' => '4 aana',
                'covered_area' => null,
                'no_of_floors' => null,
                'purpose_of_listing' => 'sale',
                'expected_selling_price' => 14000000,
                'minimum_acceptable_price' => 13200000,
                'rental_amount' => null,
                'application_no' => 'AGJ-202608-0003',
            ],
            [
                'full_name' => 'Nisha Thapa',
                'mobile_no' => '9800000004',
                'citizenship_no' => '12-01-75-00004',
                'province' => 'Bagmati',
                'district' => 'Bhaktapur',
                'municipality' => 'Bhaktapur Municipality',
                'ward_no' => '6',
                'tole_locality' => 'Suryabinayak',
                'property_type' => 'house',
                'property_code' => 'PROP-APP-004',
                'area' => '1500 sqft',
                'covered_area' => '1400 sqft',
                'no_of_floors' => 2,
                'purpose_of_listing' => 'rent',
                'expected_selling_price' => null,
                'minimum_acceptable_price' => null,
                'rental_amount' => 45000,
                'application_no' => 'AGJ-202608-0004',
            ],
            [
                'full_name' => 'Rabin Maharjan',
                'mobile_no' => '9800000005',
                'citizenship_no' => '12-01-75-00005',
                'province' => 'Lumbini',
                'district' => 'Rupandehi',
                'municipality' => 'Butwal Sub-Metropolitan City',
                'ward_no' => '9',
                'tole_locality' => 'Golpark',
                'property_type' => 'commercial_building',
                'property_code' => 'PROP-APP-005',
                'area' => '2200 sqft',
                'covered_area' => '2000 sqft',
                'no_of_floors' => 3,
                'purpose_of_listing' => 'lease',
                'expected_selling_price' => null,
                'minimum_acceptable_price' => null,
                'rental_amount' => 120000,
                'application_no' => 'AGJ-202608-0005',
            ],
            [
                'full_name' => 'Priya Joshi',
                'mobile_no' => '9800000006',
                'citizenship_no' => '12-01-75-00006',
                'province' => 'Bagmati',
                'district' => 'Nuwakot',
                'municipality' => 'Bidur Municipality',
                'ward_no' => '4',
                'tole_locality' => 'Main Road',
                'property_type' => 'land',
                'property_code' => 'PROP-APP-006',
                'area' => '3 ropani',
                'covered_area' => null,
                'no_of_floors' => null,
                'purpose_of_listing' => 'sale',
                'expected_selling_price' => 21000000,
                'minimum_acceptable_price' => 19500000,
                'rental_amount' => null,
                'application_no' => 'AGJ-202608-0006',
            ],
            [
                'full_name' => 'Manoj Khadka',
                'mobile_no' => '9800000007',
                'citizenship_no' => '12-01-75-00007',
                'province' => 'Koshi',
                'district' => 'Morang',
                'municipality' => 'Biratnagar Metropolitan City',
                'ward_no' => '15',
                'tole_locality' => 'Madhumalla',
                'property_type' => 'house',
                'property_code' => 'PROP-APP-007',
                'area' => '1300 sqft',
                'covered_area' => '1200 sqft',
                'no_of_floors' => 2,
                'purpose_of_listing' => 'sale',
                'expected_selling_price' => 7800000,
                'minimum_acceptable_price' => 7400000,
                'rental_amount' => null,
                'application_no' => 'AGJ-202608-0007',
            ],
            [
                'full_name' => 'Anita Poudel',
                'mobile_no' => '9800000008',
                'citizenship_no' => '12-01-75-00008',
                'province' => 'Gandaki',
                'district' => 'Kaski',
                'municipality' => 'Pokhara Metropolitan City',
                'ward_no' => '21',
                'tole_locality' => 'Phoolbari',
                'property_type' => 'apartment',
                'property_code' => 'PROP-APP-008',
                'area' => '1.5 BHK',
                'covered_area' => '750 sqft',
                'no_of_floors' => 5,
                'purpose_of_listing' => 'rent',
                'expected_selling_price' => null,
                'minimum_acceptable_price' => null,
                'rental_amount' => 38000,
                'application_no' => 'AGJ-202608-0008',
            ],
            [
                'full_name' => 'Dipak Paudel',
                'mobile_no' => '9800000009',
                'citizenship_no' => '12-01-75-00009',
                'province' => 'Madhesh',
                'district' => 'Bara',
                'municipality' => 'Kalaiya Sub-Metropolitan City',
                'ward_no' => '3',
                'tole_locality' => 'Ramnagar',
                'property_type' => 'commercial_building',
                'property_code' => 'PROP-APP-009',
                'area' => '2600 sqft',
                'covered_area' => '2400 sqft',
                'no_of_floors' => 4,
                'purpose_of_listing' => 'sale',
                'expected_selling_price' => 32000000,
                'minimum_acceptable_price' => 30000000,
                'rental_amount' => null,
                'application_no' => 'AGJ-202608-0009',
            ],
            [
                'full_name' => 'Smriti Tamang',
                'mobile_no' => '9800000010',
                'citizenship_no' => '12-01-75-00010',
                'province' => 'Karnali',
                'district' => 'Surkhet',
                'municipality' => 'Birendranagar Municipality',
                'ward_no' => '7',
                'tole_locality' => 'Hospital Road',
                'property_type' => 'land',
                'property_code' => 'PROP-APP-010',
                'area' => '2.5 aana',
                'covered_area' => null,
                'no_of_floors' => null,
                'purpose_of_listing' => 'sale',
                'expected_selling_price' => 16500000,
                'minimum_acceptable_price' => 15500000,
                'rental_amount' => null,
                'application_no' => 'AGJ-202608-0010',
            ],
        ];

        foreach ($items as $item) {
            $address = Address::firstOrCreate([
                'province' => $item['province'],
                'district' => $item['district'],
                'municipality' => $item['municipality'],
                'ward_no' => $item['ward_no'],
                'tole_locality' => $item['tole_locality'],
            ]);

            $client = Client::firstOrCreate(
                ['mobile_no' => $item['mobile_no']],
                [
                    'client_code' => 'CLT-' . strtoupper(Str::random(8)),
                    'client_type' => 'owner',
                    'full_name' => $item['full_name'],
                    'citizenship_no' => $item['citizenship_no'],
                    'occupation' => 'Business',
                    'email' => strtolower(str_replace(' ', '', $item['full_name'])) . '@example.com',
                    'permanent_address_id' => $address->address_id,
                    'current_address_id' => $address->address_id,
                    'registration_date' => now()->toDateString(),
                    'mis_entry_status' => 'completed',
                    'is_active' => true,
                ]
            );

            $property = Property::firstOrCreate(
                ['property_code' => $item['property_code']],
                [
                    'owner_client_id' => $client->client_id,
                    'ownership_role' => 'self',
                    'property_type' => $item['property_type'],
                    'address_id' => $address->address_id,
                    'area' => $item['area'],
                    'covered_area' => $item['covered_area'],
                    'no_of_floors' => $item['no_of_floors'],
                    'status' => 'listed',
                    'approval_status' => 'approved',
                ]
            );

            PropertyListing::firstOrCreate(
                ['application_no' => $item['application_no']],
                [
                    'property_id' => $property->property_id,
                    'applicant_client_id' => $client->client_id,
                    'purpose_of_listing' => $item['purpose_of_listing'],
                    'expected_selling_price' => $item['expected_selling_price'],
                    'minimum_acceptable_price' => $item['minimum_acceptable_price'],
                    'rental_amount' => $item['rental_amount'],
                    'negotiable' => true,
                    'date_received' => now()->toDateString(),
                    'listing_status' => 'approved',
                    'legal_verification_status' => 'completed',
                    'inspection_required' => false,
                    'valuation_required' => false,
                    'photographs_received' => true,
                    'gis_location_verified' => true,
                ]
            );
        }
    }
}
